theme: minima
title: Intendo
author: @intendo
email: no@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  intendo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
